[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "gunicorn wsgi:app"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[nixpacks]
python_version = "3.11" 