[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn wsgi:app --bind 0.0.0.0:8000"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 300 