[build]
builder = "DOCKERFILE"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "gunicorn --bind 0.0.0.0:$PORT wsgi:app"
restartPolicyType = "on_failure"
healthcheckPath = "/health"
healthcheckTimeout = 300 