[features]
seeds = false
skip-lint = false

[programs.localnet]
rwa_trade = "9AcvoQmz22KRcMhkLkeSkKs8W7ru6oae8GHcxrS83fKz"
rwa_dividend = "DvdnKLNYxRLCGJrLnYLmCTRxPXcmVvGM8x7cT8MZHnZU"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = ["src/programs/*"]
exclude = ["programs"]

[rust]
skip-idl-build = true
