[features]
seeds = false
skip-lint = false

[programs.devnet]
rwa_trade = "rwaHubTradeXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
rwa_dividend = "rwaHubDividendXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/godfather/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts" 