"""initial migration

Revision ID: 21d956e79c76
Revises: 
Create Date: 2025-02-05 16:35:15.193774

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d956e79c76'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_records', schema=None) as batch_op:
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='总分红金额(包含所有费用)',
               existing_nullable=False)
        batch_op.alter_column('actual_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='实际分配金额',
               existing_nullable=False)
        batch_op.alter_column('platform_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment=None,
               existing_comment='平台费用',
               existing_nullable=False)
        batch_op.alter_column('holders_count',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='持有人数',
               existing_nullable=False)
        batch_op.alter_column('gas_used',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment=None,
               existing_comment='gas消耗')
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(length=66),
               comment=None,
               existing_comment='交易哈希',
               existing_nullable=False)
        batch_op.drop_constraint('dividend_records_tx_hash_key', type_='unique')
        batch_op.drop_constraint('dividend_records_asset_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key('fk_dividend_records_asset_id', 'assets', ['asset_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dividend_records', schema=None) as batch_op:
        batch_op.drop_constraint('fk_dividend_records_asset_id', type_='foreignkey')
        batch_op.create_foreign_key('dividend_records_asset_id_fkey', 'assets', ['asset_id'], ['id'], ondelete='CASCADE')
        batch_op.create_unique_constraint('dividend_records_tx_hash_key', ['tx_hash'])
        batch_op.alter_column('tx_hash',
               existing_type=sa.VARCHAR(length=66),
               comment='交易哈希',
               existing_nullable=False)
        batch_op.alter_column('gas_used',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment='gas消耗')
        batch_op.alter_column('holders_count',
               existing_type=sa.INTEGER(),
               comment='持有人数',
               existing_nullable=False)
        batch_op.alter_column('platform_fee',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='平台费用',
               existing_nullable=False)
        batch_op.alter_column('actual_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='实际分配金额',
               existing_nullable=False)
        batch_op.alter_column('total_amount',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               comment='总分红金额(包含所有费用)',
               existing_nullable=False)

    # ### end Alembic commands ###
