"""add dividends table

Revision ID: 8a883b7e0fd8
Revises: 16b15760117c
Create Date: 2025-01-14 16:33:59.937008

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a883b7e0fd8'
down_revision = '16b15760117c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=20, scale=6), nullable=False, comment='分红总金额(USDC)'),
    sa.Column('created_at', sa.Date(), nullable=False, comment='分红日期'),
    sa.Column('tx_hash', sa.String(length=66), nullable=False, comment='交易哈希'),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dividends')
    # ### end Alembic commands ###
