"""Update asset status check constraint

Revision ID: a1b2c3d4e5f6
Revises: e21734bb2b34
Create Date: 2025-08-22 19:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'e21734bb2b34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('ck_status_valid', type_='check')
        batch_op.create_check_constraint('ck_status_valid', 'status IN (1, 2, 3, 4, 5, 6, 7, 8)')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_constraint('ck_status_valid', type_='check')
        batch_op.create_check_constraint('ck_status_valid', 'status IN (1, 2, 3)')

    # ### end Alembic commands ###
