"""add deployment retry count to assets table

Revision ID: a656379db413
Revises: 16956434d609
Create Date: 2025-08-21 14:44:01.339677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a656379db413'
down_revision = '16956434d609'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deployment_retry_count', sa.Integer(), server_default='0', nullable=False))
        batch_op.alter_column('contract_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)
        batch_op.alter_column('vault_address',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=64),
               existing_nullable=True)

    with op.batch_alter_table('share_messages', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               comment='权重，数值越大越容易被选中',
               existing_comment='权重，用于随机选择时的概率',
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('share_messages', schema=None) as batch_op:
        batch_op.alter_column('weight',
               existing_type=sa.INTEGER(),
               comment='权重，用于随机选择时的概率',
               existing_comment='权重，数值越大越容易被选中',
               existing_nullable=True)

    with op.batch_alter_table('assets', schema=None) as batch_op:
        batch_op.drop_column('deployment_retry_count')
        batch_op.alter_column('vault_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('contract_address',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###