"""添加上链历史记录表

Revision ID: add_onchain_history
Revises: 98fa7c6d1e32
Create Date: 2025-01-31 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'add_onchain_history'
down_revision = '98fa7c6d1e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('onchain_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('trade_id', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=50), nullable=False),
    sa.Column('onchain_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('transaction_hash', sa.String(length=100), nullable=True),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('gas_used', sa.Integer(), nullable=True),
    sa.Column('gas_price', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('triggered_by', sa.String(length=80), nullable=True),
    sa.Column('triggered_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('onchain_history', schema=None) as batch_op:
        batch_op.create_index('ix_onchain_history_asset_id', ['asset_id'], unique=False)
        batch_op.create_index('ix_onchain_history_status', ['status'], unique=False)
        batch_op.create_index('ix_onchain_history_trigger_type', ['trigger_type'], unique=False)
        batch_op.create_index('ix_onchain_history_onchain_type', ['onchain_type'], unique=False)
        batch_op.create_index('ix_onchain_history_triggered_at', ['triggered_at'], unique=False)
        batch_op.create_index('ix_onchain_history_created_at', ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('onchain_history', schema=None) as batch_op:
        batch_op.drop_index('ix_onchain_history_created_at')
        batch_op.drop_index('ix_onchain_history_triggered_at')
        batch_op.drop_index('ix_onchain_history_onchain_type')
        batch_op.drop_index('ix_onchain_history_trigger_type')
        batch_op.drop_index('ix_onchain_history_status')
        batch_op.drop_index('ix_onchain_history_asset_id')

    op.drop_table('onchain_history')
    # ### end Alembic commands ### 